### ISSUE TITLE
Beacon Ranging Problem in iOS 10.X?

### ISSUE THREAD

**Issue by njeffrey** [RoverPlatform/rover-ios#146] opened 2017-03-08 22:33 UTC
We noticed that our app stops ranging beacons on our iOS 10.X devices.  The applications work well on initial install but the next day it stops ranging completely.  Have you noticed any issues with iOS 10.X devices?

I looked in the logs and it appears the iOS isn't sending the kCLConnectionMessageWakeClient message to our application, even though it's sending it to other applications on the phone.

We also found people talking about this on the web specifically, at https://forums.developer.apple.com/thread/63792 and http://stackoverflow.com/questions/39638067/swift2-3-code-for-beacon-detection?noredirect=1#comment66581038_39638067

We're using Rover SDK 1.6.2

**Comment by seanrucker** [comment] 2017-03-09 19:29
We haven't noticed anything unusual. We have our own beacon apps installed on our phones and can confirm we have all been getting the proximity push notifications every day.

Is there any pattern to the issue? How reproduceable is it? Is it related to a specific hardware and/or OS version combination? Is your app's deployment target 9.x or 10.x?

**Comment by njeffrey** [comment] 2017-03-09 20:40
Specifically, we don't see the notifications on our iPhones 7+ running iOS 10.2.1 and our iPhone 5 running 10.2.

We do see the notifications on our iPads and iPod touches running iOS 9.X.

**Comment by seanrucker** [comment] 2017-03-09 21:10
How are you building to your device? Through Xcode or TestFlight or other?

**Comment by njeffrey** [comment] 2017-03-09 22:11
We're using our enterprise account and installing over-the-air through a link.

**Comment by seanrucker** [comment] 2017-03-09 22:24
Can you send me a build of your app?

**Comment by njeffrey** [comment] 2017-03-09 22:46
Sure.  I'll email it to you directly.

**Comment by seanrucker** [comment] 2017-03-13 15:17
I've installed the My Chemist app and added some of our office beacons to your account. I will monitor over the next few days and report back.

**Comment by seanrucker** [comment] 2017-03-16 14:44
@njeffrey I received a push immediately after installing the app and then haven't received another one since. I have the Rover Inbox app installed with the same Rover SDK on the same device and consistently receive messages from the same beacons. I'll have to assume this is related to your specific implementation. My instinct is that the location manager is being released from memory due to a weak reference. I'm going to close this issue and reach out via email as this seems related to your app and not the Rover SDK.

**Closed as completed by seanrucker** 2017-03-16 14:44 UTC
